RugbyTeamsEFMVC/Controllers/PlayerController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using RugbyTeamsEFMVC.Models;
using RugbyTeamsEFMVC.Repositories;
using RugbyTeamsEFMVC.ViewModels;

namespace RugbyTeamsEFMVC.Controllers
{
    public class PlayerController : Controller
    {
        private readonly IPlayerRepository _playerRepository;

        public PlayerController(IPlayerRepository playerRepository) 
        { 
            _playerRepository = playerRepository;
        }

        private void PositionsListViewBag()
        {
            List<string> positions = new List<string>()
            {
                "Loose-head prop",
                "Hooker",
                "Tight-head prop",
                "Second row",
                "Blind-side Flanker",
                "Open-side Flanker",
                "Number 8",
                "Scrum-half",
                "Fly-half",
                "Left wing",
                "Inside center",
                "Outside center",
                "Right wing",
                "Full back"
            };
            ViewBag.Positions = new SelectList(positions);
        }
        public IActionResult Index()
        {
            IEnumerable<Player> players = _playerRepository.GetAllPlayers();
            return View(players);
        }

        [HttpGet]
        public IActionResult CreatePlayer()
        {
            var teams = _playerRepository.GetAllTeams();
            ViewBag.Teams = new SelectList(teams, "Id", "Name");
            //List<string> positions = new List<string>()
            //{
            //    "Loose-head prop",
            //    "Hooker",
            //    "Tight-head prop",
            //    "Second row",
            //    "Blind-side Flanker",
            //    "Open-side Flanker",
            //    "Number 8",
            //    "Scrum-half",
            //    "Fly-half",
            //    "Left wing",
            //    "Inside center",
            //    "Outside center",
            //    "Right wing",
            //    "Full back"
            //};
            //ViewBag.Positions = new SelectList(positions);
            PositionsListViewBag();
            return View();
        }

        [HttpPost]
        public IActionResult CreatePlayer(PlayerViewModel player) 
        { 
            if (!ModelState.IsValid) 
            {
                var teams = _playerRepository.GetAllTeams();
                ViewBag.Teams = new SelectList(teams, "Id", "Name");
                //    List<string> positions = new List<string>()
                //{
                //    "Loose-head prop",
                //    "Hooker",
                //    "Tight-head prop",
                //    "Second row",
                //    "Blind-side Flanker",
                //    "Open-side Flanker",
                //    "Number 8",
                //    "Scrum-half",
                //    "Fly-half",
                //    "Left wing",
                //    "Inside center",
                //    "Outside center",
                //    "Right wing",
                //    "Full back"
                //};
                //    ViewBag.Positions = new SelectList(positions);
                PositionsListViewBag();
                return View(player);
            }
            _playerRepository.AddPlayer(player);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult EditPlayer(int id) 
        {
            Player player = _playerRepository.GetPlayerById(id);
            var data = new PlayerViewModel()
            {
                FirstName = player.FirstName,
                LastName = player.LastName,
                Notes = player.Notes,
                Position = player.Position,
                HeightFt = player.HeightFt,
                HeightIn = player.HeightIn,
                Weight = player.Weight,
                TeamId = player.TeamId
            };
            var teams = _playerRepository.GetAllTeams();
            ViewBag.Teams = new SelectList(teams, "Id", "Name");
            //List<string> positions = new List<string>()
            //{
            //    "Loose-head prop",
            //    "Hooker",
            //    "Tight-head prop",
            //    "Second row",
            //    "Blind-side Flanker",
            //    "Open-side Flanker",
            //    "Number 8",
            //    "Scrum-half",
            //    "Fly-half",
            //    "Left wing",
            //    "Inside center",
            //    "Outside center",
            //    "Right wing",
            //    "Full back"
            //};
            //ViewBag.Positions = new SelectList(positions);
            PositionsListViewBag();
            return View(data);
        }

        [HttpPost]
        public IActionResult EditPlayer(PlayerViewModel modifiedData)
        {
            if(!ModelState.IsValid)
            {
                return View(modifiedData);
            }
            Player player = _playerRepository.GetPlayerById(modifiedData.Id);
            player.FirstName = modifiedData.FirstName;
            player.LastName = modifiedData.LastName;
            player.Notes = modifiedData.Notes;
            player.Position = modifiedData.Position;
            player.HeightFt = modifiedData.HeightFt;
            player.HeightIn = modifiedData.HeightIn;
            player.Weight = modifiedData.Weight;
            player.TeamId = modifiedData.TeamId;
            _playerRepository.UpdatePlayer(player);
            return RedirectToAction("Index");
        }

        public IActionResult DeletePlayer(int id) 
        { 
            _playerRepository.DeletePlayer(id);
            return RedirectToAction("Index");
        }
    }
}

RugbyTeamsEFMVC/Controllers/TeamController.cs
using Microsoft.AspNetCore.Mvc;
using RugbyTeamsEFMVC.Models;
using RugbyTeamsEFMVC.Repositories;
using RugbyTeamsEFMVC.ViewModels;

namespace RugbyTeamsEFMVC.Controllers
{
    public class TeamController : Controller
    {
        private readonly ITeamRepository _teamRepository;

        public TeamController(ITeamRepository teamRepository)
        {
            _teamRepository = teamRepository;
        }
        public IActionResult Index()
        {
            IEnumerable<Team> teams = _teamRepository.GetAll();
            return View(teams);
        }

        public IActionResult GetTeamById(int id) 
        { 
            Team team = _teamRepository.GetById(id);
            List<Team> teams = new List<Team>();
            teams.Add(team);
            return View("Index", teams);
        }

        [HttpGet]
        public IActionResult CreateTeam()
        {
            return View();
        }

        [HttpPost]
        public IActionResult CreateTeam(Team team) 
        { 
            if (!ModelState.IsValid) 
            {
                return View(team);
            }
            Team newTeam = _teamRepository.Add(team);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult EditTeam(int id) 
        {
            Team team = _teamRepository.GetById(id);
            return View(team);
        }

        [HttpPost]
        public IActionResult EditTeam(Team modifiedData)
        {
            if (!ModelState.IsValid)
            {
                return View(modifiedData);
            }
            Team team = _teamRepository.GetById(modifiedData.Id);
            team.Name = modifiedData.Name;
            team.City = modifiedData.City;
            team.State = modifiedData.State;
            //team.Wins = modifiedData.Wins;
            //team.Losses = modifiedData.Losses;
            Team updatedTeam = _teamRepository.Update(team);
            return RedirectToAction("Index");
        }

        public IActionResult DeleteTeam(int id)
        {
            _teamRepository.Delete(id);
            return RedirectToAction("Index");
        }
    }
}

RugbyTeamsEFMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RugbyTeamsEFMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/RugbyTeamsEFMVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">RugbyTeamsEFMVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Team" asp-action="Index">Teams</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Player" asp-action="Index">Players</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - RugbyTeamsEFMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

RugbyTeamsEFMVC/Views/Shared/_TeamFormFields.cshtml
@* @model RugbyTeamsEFMVC.Models.Team

<div class="form-group">
    <label asp-for="Name">@Html.DisplayNameFor(model => model.Name) </label>
    <input asp-for="Name" class="form-control" />
    <span asp-validation-for="Name" class="text-danger"></span>
</div>
<div class="form-group">
    <label asp-for="City">@Html.DisplayNameFor(model => model.City) </label>
    <input asp-for="City" class="form-control" />
    <span asp-validation-for="City" class="text-danger"></span>
</div><div class="form-group">
    <label asp-for="State">@Html.DisplayNameFor(model => model.State) </label>
    <input asp-for="State" class="form-control" />
    <span asp-validation-for="City" class="text-danger"></span>
</div>
<div class="form-group">
    <label asp-for="Wins">@Html.DisplayNameFor(model => model.Wins) </label>
    <input asp-for="Wins" class="form-control" />
    <span asp-validation-for="Wins" class="text-danger"></span>
</div>
<div class="form-group">
    <label asp-for="Losses">@Html.DisplayNameFor(model => model.Losses) </label>
    <input asp-for="Losses" class="form-control" />
    <span asp-validation-for="Losses" class="text-danger"></span>
</div>
<div class="form-group">
    <button type="submit" class="btn btn-primary">Submit</button>
</div>
 *@